name: napari
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - asciitree=0.3.3
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - cloudpickle=1.5.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.23.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fasteners=0.14.1
  - freetype=2.10.2
  - gdcm=2.8.9
  - gettext=0.19.8.1
  - glib=2.65.0
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jinja2=2.11.2
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lcms2=2.11
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libjpeg-turbo=2.0.3
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - llvm-openmp=10.0.1
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - monotonic=1.5
  - msgpack-python=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.4
  - notebook=6.1.1
  - numcodecs=0.6.4
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.0
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pillow=7.2.0
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt_toolkit=3.0.5
  - pycparser=2.20
  - pydicom=2.0.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - qt=5.9.7
  - qtpy=1.9.0
  - readline=8.0
  - scikit-image=0.16.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zarr=2.4.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - alabaster==0.7.12
    - appnope==0.1.0
    - babel==2.8.0
    - cachey==0.2.1
    - chardet==3.0.4
    - dask==2.24.0
    - docutils==0.16
    - freetype-py==2.2.0
    - heapdict==1.0.1
    - idna==2.10
    - imagesize==1.2.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - napari==0.3.6
    - napari-plugin-engine==0.1.7
    - napari-svg==0.1.3
    - numpydoc==1.1.0
    - parso==0.7.1
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.6
    - psutil==5.7.2
    - ptyprocess==0.6.0
    - pyopengl==3.1.5
    - pyqt5==5.14.2
    - pyqt5-sip==12.8.0
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.6
    - requests==2.24.0
    - snowballstemmer==2.0.0
    - sphinx==3.2.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tifffile==2020.8.13
    - urllib3==1.25.10
    - vispy==0.6.4
    - wrapt==1.12.1

